// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwKTzVmCq56aMnofz6-0yy2x0KFfpknk4',
    appId: '1:961427409136:web:acef879e6c281870c6da35',
    messagingSenderId: '961427409136',
    projectId: 'fir-auth-8b54a',
    authDomain: 'fir-auth-8b54a.firebaseapp.com',
    databaseURL: 'https://fir-auth-8b54a.firebaseio.com',
    storageBucket: 'fir-auth-8b54a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RKuFSlucNbJuB7_cXTNL1kJM2iIATAA',
    appId: '1:961427409136:android:59ec9426d2893e73c6da35',
    messagingSenderId: '961427409136',
    projectId: 'fir-auth-8b54a',
    databaseURL: 'https://fir-auth-8b54a.firebaseio.com',
    storageBucket: 'fir-auth-8b54a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARad8HCysBPmG9UFHTNeWwccXHz88B7ag',
    appId: '1:961427409136:ios:fad0a6a58924f455c6da35',
    messagingSenderId: '961427409136',
    projectId: 'fir-auth-8b54a',
    databaseURL: 'https://fir-auth-8b54a.firebaseio.com',
    storageBucket: 'fir-auth-8b54a.firebasestorage.app',
    iosBundleId: 'com.example.hw12',
  );
}
